# Generated by Django 3.0.5 on 2023-07-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Dentist', 'Dentist'), ('Neurologist', 'Neurologist'), ('Family Medicine Physician', 'Family Medicine Physician'), ('Pharmacist', 'Pharmacist')], default='Cardiologist', max_length=50),
        ),
    ]
